sudo: required

language: bash

services:
  - docker

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# Build image
  - docker build -t  algoretum/django_rpi .
# Test image
#  - docker run algoretum/django_rpi python3 --version

# Push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
    TAG=Stretch_$(grep "ENV PYTHON_VER" Dockerfile | awk '{print $3}') ;
    docker tag algoretum/django_rpi algoretum/django_rpi:$TAG ;
    docker push algoretum/django_rpi:$TAG ;
    docker push algoretum/django_rpi  ;
    fi

